CREATE TABLE IF NOT EXISTS platformApiTokens (
  id TEXT NOT NULL PRIMARY KEY,
  token TEXT NOT NULL UNIQUE,
  name TEXT,
  expires INTEGER,
  revoked INTEGER,
  updated_at TEXT DEFAULT (CURRENT_TIMESTAMP),
  created_at TEXT DEFAULT (CURRENT_TIMESTAMP),
  deleted_at TEXT
);