/**
 * Core framework types
 */

/** Cloudflare Worker env â€" consumers define their own Env type */
export type Env = Record<string, any>;

/** Route context â€" passed to load functions, actions, and server utilities */
export interface RouteContext<E extends Env = Env> {
  /** The incoming Request (standard Web API) */
  request: Request;
  /** Cloudflare Worker env â€" D1, KV, R2, DO, AI, etc. */
  env: E;
  /** Cloudflare execution context */
  ctx: ExecutionContext;
  /** Route parameters (e.g., { slug: 'hello-world' }) */
  params: Record<string, string>;
  /** Request-scoped state (set by middleware, read by load/actions) */
  locals: Record<string, any>;
  /** Parsed URL */
  url: URL;
}

/** A compiled route module */
export interface RouteModule {
  /** Pattern string (e.g., '/todos', '/blog/:slug') */
  pattern: string;
  /** Load function â€" runs on GET, returns data for the template */
  load?: (ctx: RouteContext) => Promise<Record<string, any>> | Record<string, any>;
  /** Form actions â€" keyed by action name */
  actions?: Record<string, (formData: FormData, env: Env, ctx: RouteContext) => Promise<any>>;
  /** RPC functions â€" callable from client via fetch */
  rpc?: Record<string, (args: any[], env: Env, ctx: RouteContext) => Promise<any>>;
  /** Render function â€" returns HTML string from data */
  render: (data: Record<string, any>) => string;
  /** Layout name (default: 'default') */
  layout?: string;
}

/** HTTP methods supported by API routes */
export type HttpMethod = 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE' | 'HEAD' | 'OPTIONS';

/** A compiled API route module (route.ts) — returns raw Response objects */
export interface ApiRouteModule {
  /** Pattern string (e.g., '/api/v1/health', '/api/v1/db/:name') */
  pattern: string;
  /** Marker that distinguishes API routes from page routes */
  __api: true;
  /** Method handlers — keyed by HTTP method */
  [method: string]: ((ctx: RouteContext) => Promise<Response> | Response) | string | boolean;
}

/** Layout module */
export interface LayoutModule {
  /** Render function â€" wraps page content */
  render: (data: { content: string; data: Record<string, any>; head?: string }) => string;
}

/** App configuration (internal â€" used by compiler-generated code) */
export interface AppConfig<E extends Env = Env> {
  /** Route modules â€" generated by compiler or defined manually */
  routes?: (RouteModule | ApiRouteModule)[];
  /** Layout modules â€" keyed by name */
  layouts?: Record<string, LayoutModule>;
  /** Static file directory (relative to project root) */
  publicDir?: string;
}

/** Database schema config â€" maps a binding name to its schema */
export interface DatabaseConfig {
  /** Schema definition (SchemaDsl or DatabaseSchema from @kuratchi/orm) */
  schema: any;
  /** Storage type: 'd1' (default) or 'do' (Durable Object SqlStorage) */
  type?: 'd1' | 'do';
  /** Skip migrations for this database (e.g., in production). Default: false */
  skipMigrations?: boolean;
}

/**
 * Framework configuration â€" the user-facing config file (kuratchi.config.ts)
 *
 * @example
 * ```ts
 * // kuratchi.config.ts
 * import { defineConfig } from '@kuratchi/js';
 * import { todoSchema } from './src/schemas/todo';
 *
 * export default defineConfig({
 *   orm: {
 *     databases: {
 *       DB: { schema: todoSchema }
 *     }
 *   }
 * });
 * ```
 */
export interface kuratchiConfig<E extends Env = Env> {
  /** ORM configuration â€" schema definitions and auto-migration */
  orm?: {
    /** Map of D1 binding names to their database configs */
    databases?: Record<string, DatabaseConfig>;
    [key: string]: any;
  };
  /** UI configuration â€" opt into @kuratchi/ui theme and components */
  ui?: {
    /** Theme to inject: 'default' uses @kuratchi/ui's built-in theme, or a path to a custom CSS file */
    theme?: 'default' | string;
  };
  /** Auth configuration â€" @kuratchi/auth plugin setup */
  auth?: AuthConfig | Record<string, any>;
  /**
   * Durable Object configuration â€" config-driven DO class generation.
   *
   * Map a DO namespace binding to its class name and optional configuration.
   * Supports string shorthand or an object with stubId option.
   *
   * @example
   * ```ts
   * durableObjects: {
   *   // Object form â€" stubId tells the framework which user field identifies the stub
   *   ORG_DB: {
   *     className: 'OrganizationDO',
   *     stubId: 'user.orgId'
   *   },
   *   // String shorthand â€" className only, no auto-stub resolution
   *   CACHE_DB: 'CacheDO'
   * }
   * ```
   */
  durableObjects?: Record<string, string | {
    className: string;
    /** The user field path that identifies the DO stub (e.g. 'user.orgId') */
    stubId?: string;
    /** DO source files (e.g. ['auth.do.ts', 'sites.do.ts']) */
    files?: string[];
  }>;
  // Note: Containers and Workflows are auto-discovered from convention files in src/server/
  // .container.ts → FILENAME_CONTAINER binding
  // .workflow.ts  → FILENAME_WORKFLOW binding
  // No config needed — just create the file and it's automatically registered.
}

/** Auth configuration for kuratchi.config.ts */
export interface AuthConfig {
  /** Session cookie name (default: 'kuratchi_session') */
  cookieName?: string;
  /** Auth secret env binding name (default: 'AUTH_SECRET') */
  secretEnvKey?: string;
  /** Enable session parsing on every request (default: true) */
  sessionEnabled?: boolean;

  /** Credentials config â€" enables signUp/signIn/signOut/getCurrentUser */
  credentials?: {
    /** D1 binding name for auth database (default: 'DB') */
    binding?: string;
    /** Default role for new users (default: 'user') */
    defaultRole?: string;
    /** Session duration in ms (default: 30 days) */
    sessionDuration?: number;
    /** Min password length (default: 8) */
    minPasswordLength?: number;
    /** Redirect after signup (default: '/auth/login') */
    signUpRedirect?: string;
    /** Redirect after signin (default: '/admin') */
    signInRedirect?: string;
    /** Redirect after signout (default: '/auth/login') */
    signOutRedirect?: string;
    [key: string]: any;
  };

  /** Activity tracking config â€" enables logActivity/getActivity */
  activity?: Record<string, { label: string; severity?: 'info' | 'warning' | 'critical'; category?: string }>;

  /** Role definitions â€" enables hasRole/hasPermission/assignRole */
  roles?: Record<string, string[]>;

  /** OAuth providers config â€" enables startOAuth/handleOAuthCallback */
  oauth?: {
    providers?: Record<string, { clientIdEnv: string; clientSecretEnv: string; scopes?: string[] }>;
    /** Redirect after OAuth login (default: '/admin') */
    loginRedirect?: string;
    [key: string]: any;
  };

  /** Route guards â€" protect paths, redirect if not authenticated */
  guards?: {
    paths?: string[];
    exclude?: string[];
    redirectTo?: string;
    [key: string]: any;
  };

  /** Rate limiting â€" throttle requests per route */
  rateLimit?: {
    defaultWindowMs?: number;
    defaultMaxRequests?: number;
    kvBinding?: string;
    keyPrefix?: string;
    routes?: { id?: string; path: string; methods?: string[]; maxRequests?: number; windowMs?: number; message?: string }[];
    [key: string]: any;
  };

  /** Turnstile bot protection â€" verify Cloudflare Turnstile tokens */
  turnstile?: {
    /** Env var name for Turnstile secret key (default: 'TURNSTILE_SECRET') */
    secretEnv?: string;
    /** Env var name for Turnstile site key (default: 'TURNSTILE_SITE_KEY') â€" exposed to client */
    siteKeyEnv?: string;
    /** Skip Turnstile verification in dev mode (default: true) */
    skipInDev?: boolean;
    /** Routes that require Turnstile verification */
    routes?: { id?: string; path: string; methods?: string[]; tokenField?: string; tokenHeader?: string; message?: string; expectedAction?: string }[];
    [key: string]: any;
  };

  /** Organization multi-tenancy â€" DO-backed per-org databases */
  organizations?: {
    /** DO namespace binding name in env (e.g. 'ORG_DB') */
    binding?: string;
    [key: string]: any;
  } | Record<string, any>;
}





/** Runtime pipeline context - shared across runtime step handlers */
export interface RuntimeContext<E extends Env = Env> {
  request: Request;
  env: E;
  ctx: ExecutionContext;
  url: URL;
  params: Record<string, string>;
  locals: Record<string, any>;
}

export type RuntimeNext = () => Promise<Response>;

export type RuntimeErrorResult = Response | null | undefined | void;

export interface RuntimeStep<E extends Env = Env> {
  request?: (ctx: RuntimeContext<E>, next: RuntimeNext) => Promise<Response> | Response;
  route?: (ctx: RuntimeContext<E>, next: RuntimeNext) => Promise<Response> | Response;
  response?: (ctx: RuntimeContext<E>, response: Response) => Promise<Response> | Response;
  error?: (ctx: RuntimeContext<E>, error: unknown) => Promise<RuntimeErrorResult> | RuntimeErrorResult;
}

export type RuntimeDefinition<E extends Env = Env> = Record<string, RuntimeStep<E>>;
