import type { SchemaDsl } from '@kuratchi/orm';

export const authAdminTables: NonNullable<SchemaDsl['tables']> = {
  users: {
    id: 'text primary key not null',
    email: 'text not null unique',
    name: 'text',
    role: 'text',
    passwordHash: 'text',
    image: 'text',
    emailVerified: 'timestamp_ms',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  sessions: {
    sessionToken: 'text primary key not null',
    userId: 'text not null',
    expires: 'timestamp_ms not null',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  passwordResets: {
    userId: 'text not null',
    tokenHash: 'text not null',
    expiresAt: 'timestamp_ms not null',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  oauthAccounts: {
    id: 'text primary key not null',
    userId: 'text not null',
    provider: 'text not null',
    providerAccountId: 'text not null',
    accessToken: 'text',
    refreshToken: 'text',
    idToken: 'text',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  organizations: {
    id: 'text primary key not null',
    orgName: 'text',
    doName: 'text unique',
    email: 'text unique',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  userMappings: {
    id: 'text primary key not null',
    orgId: 'text not null',
    email: 'text not null unique',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  activityLog: {
    id: 'text primary key not null',
    userId: 'text',
    action: 'text not null',
    detail: 'text',
    ip: 'text',
    userAgent: 'text',
    createdAt: 'text default now',
  },
};

export const authOrgTables: NonNullable<SchemaDsl['tables']> = {
  users: {
    id: 'text primary key not null',
    email: 'text not null unique',
    name: 'text',
    role: 'text',
    passwordHash: 'text',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  sessions: {
    sessionToken: 'text primary key not null',
    userId: 'text not null',
    expires: 'timestamp_ms not null',
    createdAt: 'text default now',
    updatedAt: 'text default now',
    deletedAt: 'text',
  },
  activityLog: {
    id: 'text primary key not null',
    userId: 'text',
    action: 'text not null',
    detail: 'text',
    ip: 'text',
    userAgent: 'text',
    createdAt: 'text default now',
  },
};
