export { default as Editor } from './Editor.svelte';
export { defaultPageData } from './types';
export type { PageData, EditorOptions } from './types';
export { themes, getTheme, getAllThemes, getThemeMetadata, getThemeHomepage, getThemeTemplate, DEFAULT_THEME_ID } from './themes';
export type { ThemeMetadata, ThemeTemplate } from './themes';
export { getBlock, blocks } from './registry/blocks.svelte';
export { getLayout, layouts } from './registry/layouts.svelte';
export { getHeaderBlock, headerBlocks } from './registry/headerBlocks.svelte';
export { getFooterBlock, footerBlocks } from './registry/footerBlocks.svelte';
export { resolveBlockRender } from './render/index';
