import * as fs from 'node:fs';
import * as path from 'node:path';

import {
  type DoClassMethodEntry,
  type DoConfigEntry,
  type DoHandlerEntry,
  type OrmDatabaseEntry,
  toSafeIdentifier,
} from './compiler-shared.js';
import { discoverFilesWithSuffix } from './convention-discovery.js';

export function discoverDurableObjects(
  srcDir: string,
  configDoEntries: DoConfigEntry[],
  ormDatabases: OrmDatabaseEntry[],
): { config: DoConfigEntry[]; handlers: DoHandlerEntry[] } {
  const serverDir = path.join(srcDir, 'server');
  const legacyDir = path.join(srcDir, 'durable-objects');
  const serverDoFiles = discoverFilesWithSuffix(serverDir, '.do.ts');
  const legacyDoFiles = discoverFilesWithSuffix(legacyDir, '.ts');
  const discoveredFiles = Array.from(new Set([...serverDoFiles, ...legacyDoFiles]));

  if (discoveredFiles.length === 0) {
    return { config: configDoEntries, handlers: [] };
  }

  const configByBinding = new Map<string, DoConfigEntry>();
  for (const entry of configDoEntries) {
    configByBinding.set(entry.binding, entry);
  }

  const handlers: DoHandlerEntry[] = [];
  const discoveredConfig: DoConfigEntry[] = [];
  const fileNameToAbsPath = new Map<string, string>();
  const seenBindings = new Set<string>();

  for (const absPath of discoveredFiles) {
    const file = path.basename(absPath);
    const source = fs.readFileSync(absPath, 'utf-8');

    if (!/extends\s+DurableObject\b/.test(source)) continue;

    const classMatch = source.match(/export\s+default\s+class\s+(\w+)\s+extends\s+DurableObject/);
    const className = classMatch?.[1] ?? null;
    if (!className) continue;

    const bindingMatch = source.match(/static\s+binding\s*=\s*['"](\w+)['"]/);
    const baseName = file.replace(/\.do\.ts$/, '').replace(/\.ts$/, '');
    const derivedBinding = baseName.replace(/([a-z])([A-Z])/g, '$1_$2').toUpperCase() + '_DO';
    const binding = bindingMatch?.[1] ?? derivedBinding;

    if (seenBindings.has(binding)) {
      throw new Error(
        `[KuratchiJS] Duplicate DO binding '${binding}' detected. Use 'static binding = "UNIQUE_NAME"' in one of the classes.`,
      );
    }
    seenBindings.add(binding);

    const classMethods = extractClassMethods(source, className);

    const fileName = file.replace(/\.ts$/, '');
    const existing = fileNameToAbsPath.get(fileName);
    if (existing && existing !== absPath) {
      throw new Error(
        `[KuratchiJS] Duplicate DO handler file name '${fileName}.ts' detected:\n- ${existing}\n- ${absPath}\nRename one file or move it to avoid proxy name collision.`,
      );
    }
    fileNameToAbsPath.set(fileName, absPath);

    const configEntry = configByBinding.get(binding);
    void ormDatabases;

    discoveredConfig.push({
      binding,
      className,
      stubId: configEntry?.stubId,
      files: [file],
    });

    handlers.push({
      fileName,
      absPath,
      binding,
      mode: 'class',
      className,
      classMethods,
      exportedFunctions: [],
    });
  }

  return { config: discoveredConfig, handlers };
}

export function generateHandlerProxy(
  handler: DoHandlerEntry,
  opts: { projectDir: string; runtimeDoImport: string },
): string {
  const doDir = path.join(opts.projectDir, '.kuratchi', 'do');
  const origRelPath = path.relative(doDir, handler.absPath).replace(/\\/g, '/');
  const handlerLocal = `__handler_${toSafeIdentifier(handler.fileName)}`;
  const lifecycle = new Set(['constructor', 'fetch', 'alarm', 'webSocketMessage', 'webSocketClose', 'webSocketError']);

  const rpcFunctions = handler.classMethods
    .filter((method) => method.visibility === 'public' && !method.name.startsWith('_') && !lifecycle.has(method.name))
    .map((method) => method.name);

  const methods = handler.classMethods.map((method) => ({ ...method }));
  const methodMap = new Map(methods.map((method) => [method.name, method]));
  let changed = true;
  while (changed) {
    changed = false;
    for (const method of methods) {
      if (method.hasWorkerContextCalls) continue;
      for (const called of method.callsThisMethods) {
        const target = methodMap.get(called);
        if (target?.hasWorkerContextCalls) {
          method.hasWorkerContextCalls = true;
          changed = true;
          break;
        }
      }
    }
  }

  const workerContextMethods = methods
    .filter((method) => method.visibility === 'public' && method.hasWorkerContextCalls)
    .map((method) => method.name);
  const asyncMethods = methods.filter((method) => method.isAsync).map((method) => method.name);

  const lines: string[] = [
    `// Auto-generated by KuratchiJS compiler ï¿½" do not edit.`,
    `import { __getDoStub } from '${opts.runtimeDoImport}';`,
    `import ${handlerLocal} from '${origRelPath}';`,
    ``,
    `const __FD_TAG = '__kuratchi_form_data__';`,
    `function __isPlainObject(__v) {`,
    `  if (!__v || typeof __v !== 'object') return false;`,
    `  const __proto = Object.getPrototypeOf(__v);`,
    `  return __proto === Object.prototype || __proto === null;`,
    `}`,
    `function __encodeArg(__v, __seen = new WeakSet()) {`,
    `  if (typeof FormData !== 'undefined' && __v instanceof FormData) {`,
    `    return { [__FD_TAG]: Array.from(__v.entries()) };`,
    `  }`,
    `  if (Array.isArray(__v)) return __v.map((__x) => __encodeArg(__x, __seen));`,
    `  if (__isPlainObject(__v)) {`,
    `    if (__seen.has(__v)) throw new Error('[KuratchiJS] Circular object passed to DO RPC');`,
    `    __seen.add(__v);`,
    `    const __out = {};`,
    `    for (const [__k, __val] of Object.entries(__v)) __out[__k] = __encodeArg(__val, __seen);`,
    `    __seen.delete(__v);`,
    `    return __out;`,
    `  }`,
    `  return __v;`,
    `}`,
    `function __decodeArg(__v) {`,
    `  if (Array.isArray(__v)) return __v.map(__decodeArg);`,
    `  if (__isPlainObject(__v)) {`,
    `    const __obj = __v;`,
    `    if (__FD_TAG in __obj) {`,
    `      const __fd = new FormData();`,
    `      const __entries = Array.isArray(__obj[__FD_TAG]) ? __obj[__FD_TAG] : [];`,
    `      for (const __pair of __entries) {`,
    `        if (Array.isArray(__pair) && __pair.length >= 2) __fd.append(String(__pair[0]), __pair[1]);`,
    `      }`,
    `      return __fd;`,
    `    }`,
    `    const __out = {};`,
    `    for (const [__k, __val] of Object.entries(__obj)) __out[__k] = __decodeArg(__val);`,
    `    return __out;`,
    `  }`,
    `  return __v;`,
    `}`,
    ``,
  ];

  if (workerContextMethods.length > 0) {
    lines.push(`const __workerMethods = new Set(${JSON.stringify(workerContextMethods)});`);
    lines.push(`const __asyncMethods = new Set(${JSON.stringify(asyncMethods)});`);
    lines.push(`function __callWorkerMethod(__name, __args) {`);
    lines.push(`  const __self = new Proxy({}, {`);
    lines.push(`    get(_, __k) {`);
    lines.push(`      if (typeof __k !== 'string') return undefined;`);
    lines.push(`      if (__k === 'db') {`);
    lines.push(`        throw new Error("[KuratchiJS] Worker-executed DO method cannot use this.db directly. Move DB access into a non-public method and call it via this.<method>().");`);
    lines.push(`      }`);
    lines.push(`      if (__workerMethods.has(__k)) {`);
    lines.push(`        return (...__a) => ${handlerLocal}.prototype[__k].apply(__self, __a);`);
    lines.push(`      }`);
    lines.push(`      const __local = ${handlerLocal}.prototype[__k];`);
    lines.push(`      if (typeof __local === 'function' && !__asyncMethods.has(__k)) {`);
    lines.push(`        return (...__a) => __local.apply(__self, __a);`);
    lines.push(`      }`);
    lines.push(`      return async (...__a) => { const __s = await __getDoStub('${handler.binding}'); if (!__s) throw new Error('Not authenticated'); return __s[__k](...__a.map((__x) => __encodeArg(__x))); };`);
    lines.push(`    },`);
    lines.push(`  });`);
    lines.push(`  return ${handlerLocal}.prototype[__name].apply(__self, __args.map(__decodeArg));`);
    lines.push(`}`);
    lines.push(``);
  }

  for (const method of rpcFunctions) {
    if (workerContextMethods.includes(method)) {
      lines.push(`export async function ${method}(...a) { return __callWorkerMethod('${method}', a); }`);
    } else {
      lines.push(
        `export async function ${method}(...a) { const s = await __getDoStub('${handler.binding}'); if (!s) throw new Error('Not authenticated'); return s.${method}(...a.map((__x) => __encodeArg(__x))); }`,
      );
    }
  }

  return lines.join('\n') + '\n';
}

function extractClassMethods(source: string, className: string): DoClassMethodEntry[] {
  const classIdx = source.search(new RegExp(`class\\s+${className}\\s+extends\\s+DurableObject`));
  if (classIdx === -1) return [];

  const braceStart = source.indexOf('{', classIdx);
  if (braceStart === -1) return [];

  let depth = 0;
  let braceEnd = braceStart;
  for (let i = braceStart; i < source.length; i++) {
    if (source[i] === '{') depth++;
    else if (source[i] === '}') {
      depth--;
      if (depth === 0) {
        braceEnd = i;
        break;
      }
    }
  }

  const classBody = source.slice(braceStart + 1, braceEnd);
  const methods: DoClassMethodEntry[] = [];
  const methodRegex = /^\s+(?:(public|private|protected)\s+)?(?:(static)\s+)?(?:(async)\s+)?([A-Za-z_$][\w$]*)\s*\([^)]*\)\s*(?::[^{]+)?\{/gm;
  const reserved = new Set([
    'constructor', 'static', 'get', 'set',
    'return', 'if', 'else', 'for', 'while', 'do', 'switch', 'case',
    'throw', 'try', 'catch', 'finally', 'new', 'delete', 'typeof',
    'void', 'instanceof', 'in', 'of', 'await', 'yield', 'const',
    'let', 'var', 'function', 'class', 'import', 'export', 'default',
    'break', 'continue', 'with', 'super', 'this',
  ]);

  let match: RegExpExecArray | null;
  while ((match = methodRegex.exec(classBody)) !== null) {
    const visibility = match[1] ?? 'public';
    const isStatic = !!match[2];
    const isAsync = !!match[3];
    const name = match[4];
    if (!name || isStatic || reserved.has(name)) continue;

    const matchText = match[0] ?? '';
    const openRel = matchText.lastIndexOf('{');
    const openAbs = openRel >= 0 ? match.index + openRel : -1;
    let hasWorkerContextCalls = false;
    const callsThisMethods: string[] = [];
    if (openAbs >= 0) {
      let innerDepth = 0;
      let endAbs = openAbs;
      for (let i = openAbs; i < classBody.length; i++) {
        const ch = classBody[i];
        if (ch === '{') innerDepth++;
        else if (ch === '}') {
          innerDepth--;
          if (innerDepth === 0) {
            endAbs = i;
            break;
          }
        }
      }
      const bodySource = classBody.slice(openAbs + 1, endAbs);
      hasWorkerContextCalls = /\b(getCurrentUser|redirect|goto|getRequest|getLocals)\s*\(/.test(bodySource);
      const called = new Set<string>();
      const callRegex = /\bthis\.([A-Za-z_$][\w$]*)\s*\(/g;
      let callMatch: RegExpExecArray | null;
      while ((callMatch = callRegex.exec(bodySource)) !== null) {
        called.add(callMatch[1]);
      }
      callsThisMethods.push(...called);
    }

    methods.push({
      name,
      visibility: visibility as 'public' | 'private' | 'protected',
      isStatic,
      isAsync,
      hasWorkerContextCalls,
      callsThisMethods,
    });
  }

  return methods;
}
