import type { GenerateRoutesModuleOptions, RoutesModuleFeatureBlocks } from './routes-module-types.js';

export function buildRoutesModuleRuntimeShell(
  opts: GenerateRoutesModuleOptions,
  blocks: RoutesModuleFeatureBlocks,
): string {
  const layoutBlock = opts.compiledLayout ?? 'function __layout(content, _head = \'\') { return content; }';
  const layoutActionsBlock = opts.compiledLayoutActions
    ? `const __layoutActions = ${opts.compiledLayoutActions};`
    : 'const __layoutActions = {};';
  const componentBlock = opts.compiledComponents.length > 0 ? `// Components\n\n${opts.compiledComponents.join('\n\n')}\n` : '';
  const customErrorFunctions = Array.from(opts.compiledErrorPages.entries())
    .map(([status, fn]) => fn)
    .join('\n\n');
  const customErrorEntries = Array.from(opts.compiledErrorPages.keys())
    .map((status) => `  ${status}: __error_${status},`)
    .join('\n');
  const initializeRequestBody = [
    blocks.migrationInit ? '    await __runMigrations();' : '',
    blocks.authInit ? '    __initAuth(ctx.request);' : '',
    blocks.authPluginInit ? '    __initAuthPlugins();' : '',
    blocks.doResolverInit ? '    __initDoResolvers();' : '',
  ].filter(Boolean).join('\n');
  const preRouteChecksBody = [
    opts.authConfig?.hasRateLimit ? `    { const __rlRes = await __checkRL(); if (__rlRes) return __rlRes; }` : '',
    opts.authConfig?.hasTurnstile ? `    { const __tsRes = await __checkTS(); if (__tsRes) return __tsRes; }` : '',
    opts.authConfig?.hasGuards ? `    { const __gRes = __checkGuard(); if (__gRes) return __gRes; }` : '',
    '    return null;',
  ].filter(Boolean).join('\n');

  return `// Generated by KuratchiJS compiler - do not edit.
${opts.isDev ? '\nglobalThis.__kuratchi_DEV__ = true;\n' : ''}
${blocks.workerImport}
import { createGeneratedWorker } from '${opts.runtimeWorkerImport}';
${blocks.contextImport}
${blocks.runtimeImport ? blocks.runtimeImport + '\n' : ''}${blocks.migrationImports ? blocks.migrationImports + '\n' : ''}${blocks.authPluginImports ? blocks.authPluginImports + '\n' : ''}${blocks.doImports ? blocks.doImports + '\n' : ''}${opts.serverImports.join('\n')}
${blocks.workflowStatusRpc}

// Assets

const __assets = {
${opts.compiledAssets.map((asset) => `  ${JSON.stringify(asset.name)}: { content: ${JSON.stringify(asset.content)}, mime: ${JSON.stringify(asset.mime)}, etag: ${JSON.stringify(asset.etag)} }`).join(',\n')}
};

// Layout

${layoutBlock}

${layoutActionsBlock}

// Error pages

${customErrorFunctions ? '// Custom error page overrides (user-created NNN.html)\n' + customErrorFunctions + '\n' : ''}const __customErrors = {
${customErrorEntries}
};

${componentBlock}${blocks.migrationInit}${blocks.authInit}${blocks.authPluginInit}${blocks.doResolverInit}${blocks.doClassCode}
// Route definitions

const routes = [
${opts.compiledRoutes.join(',\n')}
];

const __runtimeDef = (typeof __kuratchiRuntime !== 'undefined' && __kuratchiRuntime && typeof __kuratchiRuntime === 'object') ? __kuratchiRuntime : {};

async function __initializeRequest(ctx) {
${initializeRequestBody || '    return;'}
}

async function __preRouteChecks() {
${preRouteChecksBody}
}

export default createGeneratedWorker({
  routes,
  layout: __layout,
  layoutActions: __layoutActions,
  assetsPrefix: ${JSON.stringify(opts.assetsPrefix)},
  assets: __assets,
  errorPages: __customErrors,
  runtimeDefinition: __runtimeDef,
  initializeRequest: __initializeRequest,
  preRouteChecks: __preRouteChecks,
  security: {
    contentSecurityPolicy: ${JSON.stringify(opts.securityConfig.contentSecurityPolicy)},
    strictTransportSecurity: ${JSON.stringify(opts.securityConfig.strictTransportSecurity)},
    permissionsPolicy: ${JSON.stringify(opts.securityConfig.permissionsPolicy)},
  },
});
`;
}
