import * as fs from 'node:fs';
import * as path from 'node:path';

export interface WorkerClassExportEntry {
  className: string;
  exportKind: 'named' | 'default';
  file: string;
}

export function resolveRuntimeImportPath(projectDir: string): string | null {
  const candidates: Array<{ file: string; importPath: string }> = [
    { file: 'src/server/runtime.hook.ts', importPath: '../src/server/runtime.hook' },
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(path.join(projectDir, candidate.file))) {
      return candidate.importPath;
    }
  }

  return null;
}

export function toWorkerImportPath(projectDir: string, outDir: string, filePath: string): string {
  const absPath = path.isAbsolute(filePath) ? filePath : path.join(projectDir, filePath);
  let rel = path.relative(outDir, absPath).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel.replace(/\.(ts|js|mjs|cjs)$/, '');
}

export function buildWorkerEntrypointSource(opts: {
  projectDir: string;
  outDir: string;
  doClassNames: string[];
  workerClassEntries: WorkerClassExportEntry[];
}): string {
  const workerClassExports = opts.workerClassEntries
    .map((entry) => {
      const importPath = toWorkerImportPath(opts.projectDir, opts.outDir, entry.file);
      if (entry.exportKind === 'default') {
        return `export { default as ${entry.className} } from '${importPath}';`;
      }
      return `export { ${entry.className} } from '${importPath}';`;
    });

  return [
    '// Auto-generated by kuratchi — do not edit.',
    "export { default } from './routes.js';",
    ...opts.doClassNames.map((className) => `export { ${className} } from './routes.js';`),
    ...workerClassExports,
    '',
  ].join('\n');
}
