import * as fs from 'node:fs';
import * as path from 'node:path';

import type { QueueConsumerEntry } from './compiler-shared.js';

export interface WorkerClassExportEntry {
  className: string;
  exportKind: 'named' | 'default';
  file: string;
}

export function resolveMiddlewareImportPath(projectDir: string): string | null {
  // Canonical request-lifecycle entrypoint.
  const candidates: Array<{ file: string; importPath: string }> = [
    // Preferred: top-level `src/middleware.ts` (matches Next.js /
    // SvelteKit conventions, visible at a glance).
    { file: 'src/middleware.ts', importPath: '../src/middleware' },
    // Fallback: co-located with server code.
    { file: 'src/server/middleware.ts', importPath: '../src/server/middleware' },
  ];

  for (const candidate of candidates) {
    if (fs.existsSync(path.join(projectDir, candidate.file))) {
      return candidate.importPath;
    }
  }

  return null;
}

export function toWorkerImportPath(projectDir: string, outDir: string, filePath: string): string {
  const absPath = path.isAbsolute(filePath) ? filePath : path.join(projectDir, filePath);
  let rel = path.relative(outDir, absPath).replace(/\\/g, '/');
  if (!rel.startsWith('.')) rel = `./${rel}`;
  return rel.replace(/\.(ts|js|mjs|cjs)$/, '');
}

export function buildWorkerEntrypointSource(opts: {
  projectDir: string;
  outDir: string;
  doClassNames: string[];
  workerClassEntries: WorkerClassExportEntry[];
  queueConsumers: QueueConsumerEntry[];
  userIndexFile?: string;
}): string {
  const doClassSet = new Set(opts.doClassNames);
  const workerClassExports = opts.workerClassEntries
    .filter((entry) => !doClassSet.has(entry.className))
    .map((entry) => {
      const importPath = toWorkerImportPath(opts.projectDir, opts.outDir, entry.file);
      if (entry.exportKind === 'default') {
        return `export { default as ${entry.className} } from '${importPath}';`;
      }
      return `export { ${entry.className} } from '${importPath}';`;
    });

  // Generate queue handler imports and dispatcher
  const queueImports: string[] = [];
  const queueDispatchCases: string[] = [];
  for (let i = 0; i < opts.queueConsumers.length; i++) {
    const consumer = opts.queueConsumers[i];
    const importPath = toWorkerImportPath(opts.projectDir, opts.outDir, consumer.file);
    const handlerName = `__queueHandler${i}`;
    if (consumer.exportKind === 'default') {
      queueImports.push(`import ${handlerName} from '${importPath}';`);
    } else {
      queueImports.push(`import { queue as ${handlerName} } from '${importPath}';`);
    }
    queueDispatchCases.push(`    case '${consumer.queueName}': return ${handlerName}(batch, env, ctx);`);
  }

  const lines = [
    '// Auto-generated by kuratchi — do not edit.',
  ];

  // Add queue handler imports if any
  if (queueImports.length > 0) {
    lines.push(...queueImports, '');
  }

  // If user has src/index.ts with a default export, merge it with the generated fetch handler
  if (opts.userIndexFile) {
    const userIndexImportPath = toWorkerImportPath(opts.projectDir, opts.outDir, opts.userIndexFile);
    lines.push(
      "import __generatedWorker from './routes';",
      `import __userWorker from '${userIndexImportPath}';`,
      '',
    );
    
    // Build the merged export with queue handler if needed
    if (queueDispatchCases.length > 0) {
      lines.push(
        '// Merge user worker exports with generated fetch and queue handlers',
        'export default {',
        '  ...__userWorker,',
        '  fetch: __generatedWorker.fetch,',
        '  async queue(batch, env, ctx) {',
        '    switch (batch.queue) {',
        ...queueDispatchCases,
        '      default:',
        '        // Fall through to user handler if defined',
        '        if (__userWorker.queue) return __userWorker.queue(batch, env, ctx);',
        `        console.warn('[kuratchi] No queue handler for:', batch.queue);`,
        '    }',
        '  },',
        '};',
      );
    } else {
      lines.push(
        '// Merge user worker exports (scheduled, queue, etc.) with generated fetch handler',
        'export default {',
        '  ...__userWorker,',
        '  fetch: __generatedWorker.fetch,',
        '};',
      );
    }
  } else if (queueDispatchCases.length > 0) {
    // No user index but we have queue consumers
    lines.push(
      "import __generatedWorker from './routes';",
      '',
      'export default {',
      '  fetch: __generatedWorker.fetch,',
      '  async queue(batch, env, ctx) {',
      '    switch (batch.queue) {',
      ...queueDispatchCases,
      '      default:',
      `        console.warn('[kuratchi] No queue handler for:', batch.queue);`,
      '    }',
      '  },',
      '};',
    );
  } else {
    lines.push("export { default } from './routes';");
  }

  lines.push(
    ...opts.doClassNames.map((className) => `export { ${className} } from './routes';`),
    ...workerClassExports,
    '',
  );

  return lines.join('\n');
}

export function buildCompatEntrypointSource(targetFile: string): string {
  return [
    '// Auto-generated by kuratchi — do not edit.',
    `export { default } from '${targetFile}';`,
    `export * from '${targetFile}';`,
    '',
  ].join('\n');
}
