import type { SchemaDsl } from '@kuratchi/orm';

export const adminSchema: SchemaDsl = {
  name: 'admin',
  version: 9,
  mixins: {
    timestamps: {
      updated_at: 'text default now',
      created_at: 'text default now',
      deleted_at: 'text'
    }
  },
  tables: {
    users: {
      id: 'text primary key not null',
      name: 'text',
      firstName: 'text',
      lastName: 'text',
      phone: 'text',
      email: 'text not null unique',
      emailVerified: 'timestamp_ms',
      image: 'text',
      status: 'boolean',
      role: 'text',
      password_hash: 'text',
      accessAttempts: 'integer',
      invite_token: 'text',
      invite_expires_at: 'timestamp_ms',
      invited_by: 'text',
      '...timestamps': true,
    },
    session: {
      sessionToken: 'text primary key not null',
      userId: 'text not null -> users.id cascade',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    passwordResetTokens: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    magicLinkTokens: {
      id: 'text primary key',
      token: 'text not null unique',
      email: 'text not null',
      redirectTo: 'text',
      consumed_at: 'timestamp_ms',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    emailVerificationToken: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      userId: 'text not null',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    oauthAccounts: {
      id: 'text primary key',
      userId: 'text -> users.id cascade',
      provider: 'text not null',
      providerAccountId: 'text not null',
      access_token: 'text',
      refresh_token: 'text',
      expires_at: 'timestamp_ms',
      scope: 'text',
      token_type: 'text',
      id_token: 'text',
      '...timestamps': true,
    },
    organizations: {
      id: 'text primary key not null',
      organizationName: 'text',
      email: 'text unique',
      organizationSlug: 'text unique',
      notes: 'text',
      status: 'enum(active,inactive,lead)',
      '...timestamps': true,
    },
    organizationUsers: {
      id: 'text primary key not null',
      email: 'text',
      organizationId: 'text',
      organizationSlug: 'text',
      '...timestamps': true,
    },
    organizationRoles: {
      id: 'text primary key not null',
      organizationId: 'text -> organizations.id',
      roleId: 'text -> roles.id',
      '...timestamps': true,
    },
    roles: {
      id: 'text primary key not null',
      name: 'text not null unique',
      description: 'text',
      permissions: 'json',
      isArchived: 'boolean default 0',
      '...timestamps': true,
    },
    permissions: {
      id: 'text primary key not null',
      value: 'text not null unique',
      label: 'text',
      description: 'text',
      isArchived: 'boolean default 0',
      '...timestamps': true,
    },
    rolePermissions: {
      id: 'text primary key not null',
      roleId: 'text -> roles.id',
      permissionId: 'text -> permissions.id',
      '...timestamps': true,
    },
    databases: {
      id: 'text primary key not null',
      name: 'text unique',
      dbuuid: 'text unique',
      workerName: 'text',
      locationHint: 'text',
      r2BucketName: 'text',
      r2Binding: 'text',
      r2StorageDomain: 'text',
      isArchived: 'boolean',
      isActive: 'boolean',
      isPrimary: 'boolean default 0',
      lastBackup: 'timestamp_ms',
      schemaVersion: 'integer default 1',
      needsSchemaUpdate: 'boolean default 0',
      lastSchemaSync: 'timestamp_ms',
      createdBy: 'text -> users.id',
      organizationId: 'text',
      siteId: 'text',
      '...timestamps': true,
    },
    kvNamespaces: {
      id: 'text primary key not null',
      name: 'text unique',
      cfNamespaceId: 'text unique',
      workerName: 'text',
      isActive: 'boolean',
      createdBy: 'text -> users.id',
      organizationId: 'text',
      '...timestamps': true,
    },
    r2Buckets: {
      id: 'text primary key not null',
      name: 'text unique',
      workerName: 'text',
      locationHint: 'text',
      isActive: 'boolean',
      createdBy: 'text -> users.id',
      organizationId: 'text',
      '...timestamps': true,
    },
    dbApiTokens: {
      id: 'text primary key not null',
      token: 'text not null unique',
      name: 'text',
      databaseId: 'text -> databases.id',
      expires: 'timestamp_ms',
      revoked: 'boolean',
      '...timestamps': true,
    },
    kvApiTokens: {
      id: 'text primary key not null',
      token: 'text not null unique',
      name: 'text',
      kvNamespaceId: 'text -> kvNamespaces.id',
      expires: 'timestamp_ms',
      revoked: 'boolean',
      '...timestamps': true,
    },
    r2ApiTokens: {
      id: 'text primary key not null',
      token: 'text not null unique',
      name: 'text',
      r2BucketId: 'text -> r2Buckets.id',
      expires: 'timestamp_ms',
      revoked: 'boolean',
      '...timestamps': true,
    },
    platformApiTokens: {
      id: 'text primary key not null',
      token: 'text not null unique',
      name: 'text',
      organizationId: 'text',
      expires: 'timestamp_ms',
      revoked: 'boolean',
      '...timestamps': true,
    },
    aiSessions: {
      id: 'text primary key not null',
      organizationId: 'text not null',
      title: 'text',
      model: 'text not null',
      lastUserMessage: 'text',
      lastAssistantMessage: 'text',
      messageCount: 'integer default 0',
      archived: 'boolean default 0',
      '...timestamps': true,
    },
    sites: {
      id: 'text primary key not null',
      name: 'text unique',
      workerName: 'text',
      customDomain: 'text',
      isActive: 'boolean',
      fileCount: 'integer default 0',
      totalSize: 'integer default 0',
      createdBy: 'text -> users.id',
      organizationId: 'text',
      '...timestamps': true,
    },
    siteFiles: {
      id: 'text primary key not null',
      siteId: 'text -> sites.id cascade',
      path: 'text not null',
      hash: 'text not null',
      contentType: 'text',
      size: 'integer default 0',
      '...timestamps': true,
    },
    siteUploads: {
      id: 'text primary key not null',
      siteId: 'text -> sites.id cascade',
      organizationId: 'text',
      uploadedBy: 'text -> users.id',
      uploadMode: 'text',
      pathPrefix: 'text',
      fileCount: 'integer default 0',
      totalSize: 'integer default 0',
      addedCount: 'integer default 0',
      overwrittenCount: 'integer default 0',
      '...timestamps': true,
    },
    siteDomains: {
      id: 'text primary key not null',
      siteId: 'text -> sites.id cascade',
      organizationId: 'text',
      hostname: 'text not null unique',
      cloudflareHostnameId: 'text unique',
      cnameTarget: 'text',
      verificationMethod: 'text',
      hostnameStatus: 'text',
      sslStatus: 'text',
      connectionStatus: 'text',
      verificationErrors: 'json',
      ownershipVerification: 'json',
      ownershipVerificationHttp: 'json',
      sslVerificationRecords: 'json',
      sslValidationErrors: 'json',
      lastCheckedAt: 'timestamp_ms',
      createdBy: 'text -> users.id',
      '...timestamps': true,
    },
    activity: {
      id: 'text primary key',
      userId: 'text',
      action: 'text not null',
      data: 'json default (json_object())',
      status: 'boolean',
      isAdminAction: 'boolean default false',
      isHidden: 'boolean default false',
      organizationId: 'text',
      ip: 'text',
      userAgent: 'text',
      '...timestamps': true,
    },
  },
} as const;
