// Auto-generated by @kuratchi/vite on first dev/build.
// Re-exports the synthesized `kuratchi:worker` module so Cloudflare
// sees every discovered convention class (workflows, durable objects,
// sandboxes, containers) as a named export off this entry, and the
// default export wires `fetch` through the Kuratchi dispatcher.
//
// You can add custom code to this file (e.g. `scheduled` handlers);
// the plugin will never overwrite it once it exists. Delete it to
// regenerate.

// @ts-expect-error — virtual module provided by `@kuratchi/vite` at build time.
export { default } from 'kuratchi:worker';
// @ts-expect-error — virtual module provided by `@kuratchi/vite` at build time.
export * from 'kuratchi:worker';
