import type { SchemaDsl } from 'kuratchi-sdk/database';
import { notificationSchemas } from 'kuratchi-sdk/notifications';

export const adminSchema: SchemaDsl = {
  name: 'admin',
  version: 12,
  mixins: {
    timestamps: {
      updated_at: 'text default now',
      created_at: 'text default now',
      deleted_at: 'text'
    }
  },
  tables: {
    users: {
      id: 'text primary key not null',
      name: 'text',
      firstName: 'text',
      lastName: 'text',
      phone: 'text',
      email: 'text not null unique',
      emailVerified: 'timestamp_ms',
      image: 'text',
      status: 'boolean', // true (active) | false (suspended) - use invite_token to detect invited
      role: 'text', // More flexible for custom roles (superadmin, owner, editor, member, etc.)
      password_hash: 'text',
      accessAttempts: 'integer',
      invite_token: 'text', // If set, user is invited (hasn't accepted yet)
      invite_expires_at: 'timestamp_ms',
      invited_by: 'text',
      '...timestamps': true,
    },
    passwordResetTokens: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    magicLinkTokens: {
      id: 'text primary key',
      token: 'text not null unique',
      email: 'text not null',
      redirectTo: 'text',
      consumed_at: 'timestamp_ms',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    emailVerificationToken: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      userId: 'text not null',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    organizationUsers: {
      id: 'text primary key not null',
      email: 'text',
      organizationId: 'text',
      organizationSlug: 'text',
      '...timestamps': true,
    },
    organizations: {
      id: 'text primary key not null',
      organizationName: 'text',
      email: 'text unique',
      organizationSlug: 'text unique',
      notes: 'text',
      stripeCustomerId: 'text',
      stripeSubscriptionId: 'text',
      sesTenantId: 'text',
      sesTenantEngagementMetrics: 'json',
      status: 'enum(active,inactive,lead)',
      '...timestamps': true,
    },
    domains: {
      id: 'text primary key not null',
      name: 'text not null',
      organizationId: 'text -> organizations.id cascade',
      emailEnabled: 'boolean default false',
      emailVerified: 'boolean default false',
      sesVerificationToken: 'text',
      sesDkimTokens: 'json',
      sesTenantId: 'text',
      emailDnsRecords: 'json',
      siteId: 'text',
      siteCustomDomainId: 'text',
      cloudflareHostnameId: 'text',
      cloudflareHostnameStatus: 'text',
      cloudflareVerification: 'json',
      '...timestamps': true,
    },
    activity: {
      id: 'text primary key',
      userId: 'text',
      action: 'text not null',
      data: 'json default (json_object())',
      status: 'boolean',
      isAdminAction: 'boolean default false',
      isHidden: 'boolean default false',
      organizationId: 'text',
      ip: 'text',
      userAgent: 'text',
      '...timestamps': true,
    },
    session: {
      sessionToken: 'text primary key not null',
      userId: 'text not null -> users.id cascade',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    oauthAccounts: {
      id: 'text primary key',
      userId: 'text -> users.id cascade',
      provider: 'text not null',
      providerAccountId: 'text not null',
      access_token: 'text',
      refresh_token: 'text',
      expires_at: 'timestamp_ms',
      scope: 'text',
      token_type: 'text',
      id_token: 'text',
      '...timestamps': true,
    },
    roles: {
      id: 'text primary key not null',
      name: 'text not null unique',
      description: 'text',
      permissions: 'json',
      isArchived: 'boolean default 0',
      '...timestamps': true,
    },
    permissions: {
      id: 'text primary key not null',
      value: 'text not null unique',
      label: 'text',
      description: 'text',
      isArchived: 'boolean default 0',
      '...timestamps': true,
    },
    databases: {
      id: 'text primary key not null',
      name: 'text unique',
      dbuuid: 'text unique',
      workerName: 'text',
      r2BucketName: 'text',
      r2Binding: 'text',
      r2StorageDomain: 'text', // Custom storage domain (e.g., subdomain.kuratchi.cloud)
      isArchived: 'boolean',
      isActive: 'boolean',
      isPrimary: 'boolean default 0',
      lastBackup: 'timestamp_ms',
      schemaVersion: 'integer default 1',
      needsSchemaUpdate: 'boolean default 0',
      lastSchemaSync: 'timestamp_ms',
      organizationId: 'text',
      siteId: 'text',
      '...timestamps': true,
    },
    dbApiTokens: {
      id: 'text primary key not null',
      token: 'text not null unique',
      name: 'text',
      databaseId: 'text -> databases.id',
      expires: 'timestamp_ms',
      revoked: 'boolean',
      '...timestamps': true,
    },
    organizationRoles: {
      id: 'text primary key not null',
      organizationId: 'text -> organizations.id',
      roleId: 'text -> roles.id',
      '...timestamps': true,
    },
    rolePermissions: {
      id: 'text primary key not null',
      roleId: 'text -> roles.id',
      permissionId: 'text -> permissions.id',
      '...timestamps': true,
    },
    emails: {
      id: 'text primary key not null',
      to: 'text not null',
      from: 'text not null',
      subject: 'text not null',
      html: 'text',
      text: 'text',
      emailType: 'text',
      status: 'enum(pending,sent,failed) default pending',
      error: 'text',
      resendId: 'text',
      sentAt: 'timestamp_ms',
      userId: 'text',
      organizationId: 'text',
      metadata: 'json',
      '...timestamps': true,
    },
    email_message_lookup: {
      id: 'text primary key not null',
      sesMessageId: 'text unique not null',
      organizationId: 'text not null',
      '...timestamps': true,
    },
    stripeCustomers: {
      id: 'text primary key not null',
      stripeCustomerId: 'text unique not null',
      email: 'text',
      name: 'text',
      organizationId: 'text -> organizations.id',
      metadata: 'json',
      '...timestamps': true,
    },
    stripeSubscriptions: {
      id: 'text primary key not null',
      stripeSubscriptionId: 'text unique not null',
      stripeCustomerId: 'text not null',
      stripePriceId: 'text not null',
      stripeProductId: 'text not null',
      status: 'text not null',
      currentPeriodStart: 'timestamp_ms',
      currentPeriodEnd: 'timestamp_ms',
      cancelAtPeriodEnd: 'boolean default 0',
      canceledAt: 'timestamp_ms',
      metadata: 'json',
      '...timestamps': true,
    },
    stripeProducts: {
      id: 'text primary key not null',
      stripeProductId: 'text unique not null',
      name: 'text not null',
      description: 'text',
      active: 'boolean default 1',
      features: 'json',
      metadata: 'json',
      '...timestamps': true,
    },
    stripePrices: {
      id: 'text primary key not null',
      stripePriceId: 'text unique not null',
      stripeProductId: 'text not null',
      unitAmount: 'integer not null',
      currency: 'text not null default usd',
      recurringInterval: 'text',
      recurringIntervalCount: 'integer',
      active: 'boolean default 1',
      metadata: 'json',
      '...timestamps': true,
    },
    stripeEvents: {
      id: 'text primary key not null',
      stripeEventId: 'text unique not null',
      type: 'text not null',
      data: 'json not null',
      processed: 'boolean default 0',
      processedAt: 'timestamp_ms',
      '...timestamps': true,
    },
    stripeInvoices: {
      id: 'text primary key not null',
      stripeInvoiceId: 'text unique not null',
      stripeCustomerId: 'text not null',
      stripeSubscriptionId: 'text',
      amountDue: 'integer not null',
      amountPaid: 'integer not null',
      currency: 'text not null',
      status: 'text not null',
      hostedInvoiceUrl: 'text',
      invoicePdf: 'text',
      metadata: 'json',
      '...timestamps': true,
    },
    platformApiTokens: {
      id: 'text primary key not null',
      token: 'text not null unique',
      name: 'text',
      expires: 'timestamp_ms',
      revoked: 'boolean',
      '...timestamps': true,
    },
    // =========== OEM CATALOG TABLES ===========
    catalogOems: {
      id: 'text primary key not null',
      name: 'text not null',
      logo_url: 'text',
      website_url: 'text',
      description: 'text',
      '...timestamps': true,
    },
    catalogVehicles: {
      id: 'text primary key not null',
      oem_id: 'text not null -> catalogOems.id cascade',
      oem_name: 'text not null',
      model_name: 'text not null',
      model_year: 'integer',
      category: 'enum(atv,utv,dirtbike,pitbike,motorcycle,electric,other) default other',
      msrp: 'integer',
      currency: 'text default USD',
      source_url: 'text',
      thumbnail_url: 'text',
      images: 'json default (json_array())',
      specifications: 'json default (json_object())',
      features: 'json default (json_array())',
      description: 'text',
      status: 'enum(draft,published,archived) default draft',
      '...timestamps': true,
    },
    catalogVehicleImages: {
      id: 'text primary key not null',
      vehicle_id: 'text not null -> catalogVehicles.id cascade',
      url: 'text not null',
      alt_text: 'text',
      is_primary: 'boolean default 0',
      sort_order: 'integer default 0',
      '...timestamps': true,
    },
    catalogCategories: {
      id: 'text primary key not null',
      name: 'text not null',
      slug: 'text not null unique',
      description: 'text',
      parent_id: 'text',
      sort_order: 'integer default 0',
      '...timestamps': true,
    },
    catalogSpecTemplates: {
      id: 'text primary key not null',
      category: 'text',
      name: 'text not null',
      label: 'text not null',
      unit: 'text',
      input_type: 'enum(text,number,select) default text',
      options: 'json',
      sort_order: 'integer default 0',
      '...timestamps': true,
    },
    // Notification tables
    ...notificationSchemas,
  },
} as const;
