import type { SchemaDsl } from 'kuratchi-sdk/database';

export const organizationSchema: SchemaDsl = {
  name: 'organization',
  version: 4,
  mixins: {
    timestamps: {
      updated_at: 'text default now',
      created_at: 'text default now',
      deleted_at: 'text'
    }
  },
  tables: {
    users: {
      id: 'text primary key not null',
      name: 'text',
      firstName: 'text',
      lastName: 'text',
      phone: 'text',
      email: 'text not null unique',
      emailVerified: 'timestamp_ms',
      image: 'text',
      status: 'boolean',
      role: 'enum(owner,editor,member)',
      password_hash: 'text',
      accessAttempts: 'integer',
      tenantId: 'text',
      organization: 'text',
      '...timestamps': true,
    },
    session: {
      sessionToken: 'text primary key not null',
      userId: 'text not null -> users.id cascade',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    passwordResetTokens: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    emailVerificationToken: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      userId: 'text not null',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    magicLinkTokens: {
      id: 'text primary key',
      token: 'text not null',
      email: 'text not null',
      redirectTo: 'text',
      consumed_at: 'timestamp_ms',
      expires: 'timestamp_ms not null',
      '...timestamps': true,
    },
    activity: {
      id: 'text primary key',
      userId: 'text',
      action: 'text not null',
      data: 'json default (json_object())',
      status: 'boolean',
      isAdminAction: 'boolean default false',
      ip: 'text',
      userAgent: 'text',
      '...timestamps': true,
    },
    roles: {
      id: 'text primary key',
      name: 'text not null',
      description: 'text',
      permissions: 'json',
      '...timestamps': true,
    },
    oauthAccounts: {
      id: 'text primary key',
      userId: 'text -> users.id cascade',
      provider: 'text not null',
      providerAccountId: 'text not null',
      access_token: 'text',
      refresh_token: 'text',
      id_token: 'text',
      expires_at: 'timestamp_ms',
      scope: 'text',
      token_type: 'text',
      '...timestamps': true,
    },
    sites: {
      id: 'text primary key not null',
      name: 'text',
      subdomain: 'text',
      description: 'text',
      status: 'boolean',
      environment: 'enum(production,preview)',
      theme: 'text',
      databaseId: 'text',
      dbuuid: 'text',
      workerName: 'text',
      r2BucketName: 'text',
      r2Binding: 'text',
      metadata: 'json',
      '...timestamps': true,
    },
    siteCustomDomains: {
      id: 'text primary key not null',
      siteId: 'text -> sites.id cascade',
      domain: 'text not null',
      domainId: 'text',
      verified: 'boolean default false',
      cnameTarget: 'text',
      verificationToken: 'text',
      cloudflareStatus: 'text',
      cloudflareHostnameId: 'text',
      sslStatus: 'text',
      '...timestamps': true,
    },
    userSites: {
      userId: 'text -> users.id cascade',
      siteId: 'text -> sites.id cascade',
      '...timestamps': true,
    },
    email_logs: {
      id: 'text primary key not null',
      recipient: 'text not null default ""',
      sender: 'text not null default ""',
      subject: 'text not null default ""',
      emailType: 'text',
      status: 'enum(sent,delivered,bounced,complained,rejected,failed,pending) default pending',
      sesMessageId: 'text',
      error: 'text',
      userId: 'text -> users.id',
      metadata: 'json',
      sentAt: 'text',
      deliveredAt: 'text',
      deliveryDelay: 'integer',
      openedAt: 'text',
      openCount: 'integer default 0',
      userAgent: 'text',
      clickedAt: 'text',
      clickCount: 'integer default 0',
      lastClickedLink: 'text',
      bouncedAt: 'text',
      bounceType: 'text',
      bounceSubType: 'text',
      complainedAt: 'text',
      complaintFeedbackType: 'text',
      rejectedAt: 'text',
      rejectReason: 'text',
      deliveryDelayed: 'boolean default false',
      deliveryDelayType: 'text',
      '...timestamps': true,
    },
    broadcasts: {
      id: 'text primary key not null',
      name: 'text not null default ""',
      subject: 'text not null default ""',
      html: 'text not null default ""',
      segmentId: 'text not null',
      segmentName: 'text default ""',
      status: 'enum(draft,sending,sent,failed) default draft',
      scheduledAt: 'text',
      sentAt: 'text',
      totalRecipients: 'integer default 0',
      sentCount: 'integer default 0',
      deliveredCount: 'integer default 0',
      openedCount: 'integer default 0',
      clickedCount: 'integer default 0',
      bouncedCount: 'integer default 0',
      '...timestamps': true,
    },
  },
} as const;
