export const sitesSchema: any = {
    name: 'sites',
    version: 1.1,
    mixins: {
      timestamps: {
        updated_at: 'text default now',
        created_at: 'text default now',
        deleted_at: 'text'
      }
    },
    tables: {
        pages: {
            id: 'text primary key not null',
            title: 'text',
            data: 'json default (json_object())',
            seoTitle: 'text',
            seoDescription: 'text',
            slug: 'text unique',
            isSpecialPage: 'boolean',
            pageType: 'enum(homepage, webpage)',
            status: 'boolean',
            '...timestamps': true,
        },
        media: {
            id: 'text primary key not null',
            key: 'text',
            url: 'text',
            fileName: 'text',
            alt: 'text',
            '...timestamps': true,
        },
        slides: {
            id: 'text primary key not null',
            title: 'text',
            alt: 'text',
            src: 'text',
            key: 'text',
            status: 'boolean',
            '...timestamps': true,
        },
        menu: {
            id: 'text primary key not null',
            name: 'text',
            menuItems: 'json default (json_array())',
            status: 'boolean',
            '...timestamps': true,
        },
        popups: {
            id: 'text primary key not null',
            name: 'text',
            formId: 'text',
            data: 'json default (json_object())',
            image: 'json default (json_array())',
            status: 'boolean',
            deliveryMethod: 'enum(On Page Load, On First Click)',
            deliveryPage: 'enum(Homepage, Anywhere)',
            deliveryDelay: 'integer',
            deliveryRepeat: 'integer',
            deliveryStyle: 'enum(Modal, Slide In, Full Page)',
            '...timestamps': true,
        },
        products: {
            id: 'text primary key not null',
            name: 'text',
            description: 'text',
            price: 'text',
            slug: 'text unique',
            sku: 'text',
            ctaText: 'text',
            featureText: 'text',
            featureImage: 'text',
            images: 'json default (json_array())',
            features: 'json default (json_array())',
            category: 'text',
            subcategory: 'text',
            tags: 'json default (json_array())',
            status: 'enum(published, draft, archived)',
            '...timestamps': true,
        },
        categories: {
            id: 'text primary key not null',
            name: 'text',
            entity: 'enum(product, service, post)',
            '...timestamps': true,
        },
        subcategories: {
            id: 'text primary key not null',
            name: 'text',
            categoryId: 'text references categories(id) on delete cascade',
            '...timestamps': true,
        },
        tags: {
            id: 'text primary key not null',
            name: 'text',
            entity: 'enum(product, service, post)',
            '...timestamps': true,
        },
        entityTags: {
            id: 'text primary key not null',
            tagId: 'text references tags(id) on delete cascade',
            entityId: 'text',
            '...timestamps': true,
        },
        entityCategories: {
            id: 'text primary key not null',
            categoryId: 'text references categories(id) on delete cascade',
            entityId: 'text',
            '...timestamps': true,
        },
        entitySubcategories: {
            id: 'text primary key not null',
            subcategoryId: 'text references subcategories(id) on delete cascade',
            entityId: 'text',
            '...timestamps': true,
        },
        services: {
            id: 'text primary key not null',
            name: 'text',
            description: 'text',
            price: 'text',
            slug: 'text',
            ctaText: 'text',
            featureText: 'text',
            featureImage: 'text',
            images: 'json default (json_array())',
            features: 'json default (json_array())',
            category: 'text',
            subcategory: 'text',
            tags: 'json default (json_array())',
            status: 'enum(published, draft, archived)',
            '...timestamps': true,
        },
        posts: {
            id: 'text primary key not null',
            seoTitle: 'text',
            seoDescription: 'text',
            content: 'json default (json_array())',
            slug: 'text',
            status: 'enum(published, draft, archived)',
            authorId: 'text -> users.id',
            '...timestamps': true,
        },
        comments: {
            id: 'text primary key not null',
            name: 'text',
            email: 'text',
            comment: 'text',
            postId: 'text -> posts.id cascade',
            status: 'text',
            '...timestamps': true,
        },
        forms: {
            id: 'text primary key not null',
            name: 'text',
            description: 'text',
            responseMessage: 'text',
            fields: 'json default (json_array())',
            ctaButton: 'json default (json_array())',
            status: 'boolean',
            timestamp: 'text default now',
            recipients: 'json default (json_array())',
            deliveryMethod: 'enum(On Page Load, On First Click)',
            deliveryPage: 'enum(Homepage, Anywhere)',
            deliveryDelay: 'integer',
            deliveryRepeat: 'integer',
            deliveryStyle: 'enum(Modal, Slide In, Full Page)',
            '...timestamps': true,
        },
        leads: {
            id: 'text primary key not null',
            formId: 'text -> forms.id cascade',
            data: 'json default (json_array())',
            status: 'boolean',
            '...timestamps': true,
        },
        redirects: {
            id: 'text primary key not null',
            source: 'text',
            destination: 'text',
            code: 'text',
            '...timestamps': true,
        },
        newsletter: {
            id: 'text primary key not null',
            domain: 'text',
            status: 'boolean',
            '...timestamps': true,
        },
        subscribers: {
            id: 'text primary key not null',
            email: 'text',
            status: 'boolean',
            audienceId: 'text',
            contactResendId: 'text',
            '...timestamps': true,
        },
        campaigns: {
            id: 'text primary key not null',
            name: 'text',
            subject: 'text',
            body: 'text',
            status: 'boolean',
            audienceId: 'text',
            '...timestamps': true,
        },
        audiences: {
            id: 'text primary key not null',
            name: 'text',
            description: 'text',
            audienceResendId: 'text',
            status: 'boolean',
            '...timestamps': true,
        },
        scripts: {
            id: 'text primary key not null',
            name: 'text',
            attributes: 'json default (json_array())',
            isEnabled: 'boolean',
            '...timestamps': true,
        }
    }
};
